// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bookfortablefront.Models;

public partial class MyCoupon
{
    public int McId { get; set; }

    public int DicountId { get; set; }

    public int MemberId { get; set; }

    public virtual DiscountCodeCart Dicount { get; set; }

    public virtual Member Member { get; set; }
}