// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookForTableAPI.Models;

public partial class BookTag
{
    public int BtagId { get; set; }

    public string BtagName { get; set; }

    public virtual ICollection<Relation> Relations { get; set; } = new List<Relation>();
}