// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookForTableAPI.Models;

public partial class TempBox
{
    public int BoxId { get; set; }

    public decimal? Price { get; set; }

    public string BookTag2string { get; set; }
}