// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bookfortable.Models;

public partial class BlogImage
{
    public int ImageId { get; set; }

    public int BlogId { get; set; }

    public string ImageTitle { get; set; }

    public string ImagePath { get; set; }
}