// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bookfortable.Models;

public partial class OrderDetail
{
    public int Odid { get; set; }

    public string OrderDetailId { get; set; }

    public int? TempBoxId { get; set; }

    public string BookTag2string { get; set; }

    public int? ProductAmount { get; set; }

    public decimal? Price { get; set; }

    public virtual ICollection<OrderList> OrderLists { get; set; } = new List<OrderList>();

    public virtual ICollection<PickingOrder> PickingOrders { get; set; } = new List<PickingOrder>();

    public virtual TempBox TempBox { get; set; }
}