// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bookfortable.Models;

public partial class PickingOrder
{
    public int Pkoid { get; set; }

    public string Pkoramd { get; set; }

    public int? OrderListId { get; set; }

    public int? OrderDetailsId { get; set; }

    public int? ProductId { get; set; }

    public int? EmployeeId { get; set; }

    public int? TempBoxId { get; set; }

    public decimal? PriceRange { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual OrderDetail OrderDetails { get; set; }

    public virtual OrderList OrderList { get; set; }

    public virtual Product Product { get; set; }

    public virtual TempBox TempBox { get; set; }
}