// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bookfortable.Models;

public partial class QuestionRecord
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? ResultId { get; set; }

    public DateOnly? Date { get; set; }

    public virtual Member Member { get; set; }

    public virtual Result Result { get; set; }
}